# Generated by Django 5.1.4 on 2025-11-04 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='referenced_movies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
