# Generated by Django 5.1.4 on 2025-11-04 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_chatconversation_referenced_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatconversation',
            name='system_prompt_sent',
            field=models.BooleanField(default=False),
        ),
    ]
