# Generated by Django 5.2.7 on 2025-12-04 08:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0005_add_hnsw_index'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='moviesection',
            name='embedding',
        ),
    ]
